- link:
    "~/AppData/Roaming/Local/enabled-addons.json": local/enabled-addons.json
    "~/AppData/Roaming/Local/error-reporting.json": local/error-reporting.json
    "~/AppData/Roaming/Local/settings-new-site-defaults.json": local/settings-new-site-defaults.json
    "~/AppData/Local/Programs/Local/resources/extraResources/lightning-services/php-7.3.5+3/bin/win32/php.ini": local/conf/php.ini

- create:
    - "~/AppData/Roaming/Local/addons"

- shell:
    - [bash ./bin/install-local-addons.sh, Installing Local addons]
